plugins {
    id 'java-library'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = "$game_version-$mod_version"
group = 'com.github.kay9.dragonmounts'

repositories {
    mavenLocal()

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)
minecraft.accessTransformers.file file('src/main/resources/META-INF/accesstransformer.cfg')

sourceSets {
    // include generated resources
    main.resources { srcDir 'src/generated/resources' }

    // include example addon
//    exampleAddon.resources { srcDir 'example_addon' }
}

runs {
    configureEach {
        systemProperty 'forge.logging.console.level', 'debug'

        modSources {
            add project.sourceSets.main
//            add project.sourceSets.exampleAddon
        }
    }

    client {
        programArguments.addAll '--username', 'Player###'
    }

    server {
        programArgument '--nogui'
    }

    data {
        programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    localRuntime "mezz.jei:jei-${game_version}-neoforge:${jei_version}"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: game_version,
            minecraft_version_range: game_version_range,
            neo_version: neo_version,
            neo_version_range: neo_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_description: mod_description,
            mod_version: mod_version,
            license: license
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

// Example for how to get properties into the manifest for reading at runtime.
tasks.named('jar', Jar).configure {
    // data-gen artifacts aren't necessary in release builds.
    exclude('com/github/kay9/dragonmounts/data/providers/**')
    exclude('.cache')
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}