# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.21.1
# https://github.com/ParchmentMC/Parchment/tags
neogradle.subsystems.parchment.mappingsVersion=2024.11.17

java_version = 21

game_version = 1.21.1
game_version_range = [1.21,1.21.1)

neo_version = 21.1.1
neo_version_range = [21.1.1,)
loader_version_range = [4,)

mod_id = dragonmounts
mod_name = Dragon Mounts: Legacy
mod_description = This is a mod that allows you to hatch previously useless dragon eggs.\nOnce fostered and tamed, they'll be your faithful companion in all situations and, of course, can be used for a ride!
# Default to 999.
# Actual release versions are acquired from the git tag and passed into the build args.
mod_version = 999
# https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack#%22pack_format%22
license = GNU GPLv3

#https://modrinth.com/mod/jei/versions
jei_version = 19.21.1.304