modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/Kay9Unit/Dragon-Mounts-Legacy/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#logoFile="examplemod.png"
credits='''
ata4/barracuda - original project and idea.
Mojang - Base game and sound assets.
'''
authors="Kay9"
description='''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
