name: Publish Release CI

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Build with Gradle
        # `#*-` : strip out the game version from the ref tag
        run: |
          ./gradlew build -Pmod_version=${GITHUB_REF_NAME#*-}

      - name: Publish jar
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: G3EPcczP
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 375088
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GH_TOKEN }}